# 7-base_geometry.txt
# Adam Taylor <2680@holbertonschool.com>

===========================
Usage of 7-base_geometry.py
===========================

This module creates a class 'BaseGeometry' that has
two seperate functions that raise different exceptions and errors

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
    >>> bg = BaseGeometry()

::

    >>> bg.integer_validator("my_int", 12)

::

    >>> bg.integer_validator("width", 89)

::

    >>> bg.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

::

    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
    ...
    ValueError: age must be greater than 0

::

    >>> bg.integer_validator("hank", -5)
    Traceback (most recent call last):
    ...
    ValueError: hank must be greater than 0

::

    >>> bg.integer_validator("hank", "hill")
    Traceback (most recent call last):
    ...
    TypeError: hank must be an integer

::

    >>> bg.integer_validator("hank", 0.5)
    Traceback (most recent call last):
    ...
    TypeError: hank must be an integer

::

    >>> bg.integer_validator("string", 5)

::

    >>> bg.integer_validator("hank", [100])
    Traceback (most recent call last):
    ...
    TypeError: hank must be an integer

::

    >>> bg.integer_validator("hank", (3, 3))
    Traceback (most recent call last):
    ...
    TypeError: hank must be an integer

::

    >>> bg.integer_validator("hank", {1, 0})
    Traceback (most recent call last):
    ...
    TypeError: hank must be an integer

::

    >>> bg.integer_validator("hank", True)

::

    >>> bg.integer_validator("hank", False)
    Traceback (most recent call last):
    ...
    ValueError: hank must be greater than 0

::

    >>> bg.integer_validator("hank", None)
    Traceback (most recent call last):
    ...
    TypeError: hank must be an integer

::

    >>> bg.integer_validator("hank")
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

::

    >>> bg.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
